- name: Setup Elasticsearch
  hosts: all
  roles:
    - role: elastic.elasticsearch
  pre_tasks:
    - name : install dependencies before starting
      become: yes
      apt:
        name: 
          - gnupg2
        state: latest
        update_cache: yes
  vars:
    es_version: 7.17.0
    es_heap_size: 128m
    es_config:
      node.name: "{{ es_node_name }}"
      cluster.name: "mycluster"
      cluster.initial_master_nodes: "{{ initial_master_nodes if bootstrap_es else '' }}"
      discovery.seed_hosts: "{{ discovery_seed_hosts }}"
      bootstrap.memory_lock: true
      http.host: 0.0.0.0
      transport.host: 0.0.0.0
    es_api_basic_auth_username: "elastic" 
    es_api_basic_auth_password: "{{ elastic_user_password }}"
    es_enable_http_ssl: true
    es_enable_transport_ssl: true
    es_ssl_key: "files/server.key"
    es_ssl_certificate: "files/server.cert"
    es_ssl_certificate_authority: "files/ca.cert"
